- .graphqlconfig.yml
- amplify/backend/api/neighbourhood/schema.graphql
Added convention, replace circular hasManywith manyToMany, and added missing relationships to be able to use belongsTo.
> Refactor schema 

- amplify/backend/backend-config.json
- amplify/backend/types/amplify-dependent-resources-ref.d.ts
- amplify/team-provider-info.json
Added s3 storage using amplify cli commands, ran amplify push, updated dependencies
> NEIG-39: Add s3 storage bucket

- app/page.tsx
Just added 'use client' to the landing page.tsx so that things render properly
> Quick Hotfix (Client-Side Rendering)

- app/events/page.tsx
- app/home/page.tsx
- app/layout.tsx
- app/marketplace/page.tsx
- app/people/page.tsx
- components/CreateEventDrawer/CreateEventDrawer.tsx
- components/EventCard/EventCard.module.css
- components/EventCard/EventCard.tsx
- components/Navbar/Navbar.module.css
- components/NeighbourhoodShell/NeighbourhoodShell.tsx
- components/ViewEventModal/ViewEventModal.module.css
- components/ViewEventModal/ViewEventModal.tsx
- package-lock.json
- package.json
- types/types.ts
https://github.com/br-cz/neighbourhood/assets/93398491/323fae4a-fe3a-4ebe-9fa0-6cc61a3089bb
- The EventCard component represents what one event will look like in the feed
- Contains the event's image, name, organizer, location, date/time, # attendees, and some actions (view, rsvp, save) that can be adjusted if need be
- Added a page header with search/sort controls that can be in reworked across all of our different pages (maybe worth modularizing idk)
- Used Mantine's SimpleGrid to take in events and display their EventCards in a size-responsive grid view
- Also added an Event Creation Drawer and Event Details Modal which I'll describe below
- The "View" Button on an EventCard can be clicked to display a customized Modal preview of the event
- Basically the same thing but with the full …
> AK-NEIG-49: Event Feed, Event Card, Event Creation 

- app/communities/page.tsx
- app/events/page.tsx
- app/home/page.tsx
- app/marketplace/page.tsx
- app/page.tsx
- app/people/page.tsx
- app/profile/page.tsx
- components/Authorization/useAuth.ts
useAuth() checks if user is logged in, other redirects them to login!
Not best practice to have a bunch of comments everywhere + unused loading variable, but would make it easy to later implement some form of message as to why users are being redirected.
> BC-NEIG-13: Check authorization fo every page

- src/api/memberQueries.ts
We get the list of all usercommunities, and filter it down to only items related to our current community!
> BC-NEIG-23: Get current members of current community

- components/CommunityButton/CommunityButton.module.css
- components/EventCard/EventCard.module.css
- components/Navbar/Navbar.module.css
- components/UserButton/UserButton.module.css
- components/UserListItem/UserListItem.module.css
https://github.com/br-cz/neighbourhood/assets/93398491/07ea27e4-4c4c-4b87-b36d-f0d61e5deaff
Super quick change, just added hover animations to the event cards that we can carry over to the other cards as well.
Also smoothened transitions when hovering the navbar & people list
> NEIG-59: Added Hover Animations to Cards

- components/Authorization/signUpForm.client.tsx
Temporarily restricting community for demo purposes - will replace later on!
> Default Community to UManitoba on Signup

- app/home/page.tsx
- components/CreatePostDrawer/CreatePostDrawer.tsx
- components/EventCard/EventCard.module.css
- components/PostCard/PostCard.module.css
- components/PostCard/PostCard.tsx
https://github.com/br-cz/neighbourhood/assets/93398491/dd4ccacf-4c10-4024-86d5-ccdfdb0e1a70
- Uses placeholder data to render PostCards, we'll just need to toss a useFetchPosts() function in here to get the posts based on the current community ID, ezpz
- New component, represents a single post
- Takes in a post to get its data + display it within the card
- ❗ We'll need a function for timestamps probably (converted postedAt to a readable string) - maybe worth a timeUtils file?
- Modified the CreateEventDrawer that was already built, opens upon clicking "new post"
- Might reduce the width, not sure how I feel ab that yet
- Inputs are just the post content (textarea) and post visibility (select)
- ❗ I commented out things related to image upload, not sure if we should include image uploads …
> NEIG-42: Post Feed + Creation Frontend

- amplify/backend/api/neighbourhood/schema.graphql
- components/UserList/UserList.tsx
- components/UserListItem/UserListItem.tsx
- src/api/friendQueries.ts
- Tweaked graphql schema to remove unnecessary friend request enum, added sender and receiver for friend requests and made friends a string array of friend user id's instead to remove gaps in dynamodb's faults when it comes to many to many relationships (or maybe its my skill issue)
- Tweaked user list and user list item to use new hooks related to friends
- Added ability to see friends, incoming and outgoing friend requests and non friends in community. Also added ability to create friends and friend requests
> Bc neig 22

- components/SignUp/SignUp.tsx
Adding an entry in UserCommunity follows the easy many to many relationship handling. Uses new user id and their selected community
> NEIG-70: Add user to their selected community

- amplify/backend/api/neighbourhood/schema.graphql
- src/graphql/schema.json
Quick lil amplify pull + codegen to make sure the schema is fixed after the past few merges
> Schema Hotfix

- components/CreatePostDrawer/CreatePostDrawer.module.css
- components/CreatePostDrawer/CreatePostDrawer.tsx
- components/CreatePostDrawer/createPostValidation.ts
Implemented post creation validation when user tries to make a new post. 
The following files have been modified or added:
* CreatePostDrawer.tsx - Reworked to use Formik for validation on user inputs.
* createPostValidation.tsx (_New_)- Implements the schema using yup
* CreatePostDrawer.module.tsx (_New_)- Implements the style sheet. Currently used to only make the error message font in red.
> NEIG-51 Home: Post Creation Form Validation

- components/CommunityListItem/CommunityListItem.tsx
- components/UserListItem/UserListItem.tsx
- types/types.ts
Typing was messing up npm run build. After this hot fix, npm run build should work flawlessly for CI.
> Add types and fix type issue

- utils/timeUtils.ts
Added default string for no time events as well processed events properly by getting time
> Fix time utils throwing error

- __test__/SignUp.test.tsx
- components/CommunityListItem/CommunityListItem.tsx
- components/SignUp/AddressInput.tsx
- components/SignUp/LoginDetails.tsx.tsx
- components/SignUp/ProfileSetup.tsx
- components/SignUp/SelectCommunity.tsx
- components/SignUp/SignUp.tsx
A suite of unit tests covering the signup process, both related to the frontend as well as form validation across each step. Cognito profile creation itself is not covered. All tests pass with no issues.
Some are commented out currently as they rely on the PR that still needs merge, will uncomment after 👍🏼 
- Renders the initial page and stepper correctly
- Renders step 1 login detail fields correctly
- Successfully selects and changes input fields
- Navigates to Step 2 on valid input
- Doesn't navigate to Step 2 if fields are missing
- Doesn't navigate to Step 2 if email is present but invalid
- Doesn't navigate to Step 2 if password is present but too short
- Doesn't navigate to Step 2 if passwords are present but don't match
- Renders step 2 address field correctly
- Step 2 field is …
> NEIG-108: SignUp Process Unit Tests

- __test__/logInDetails.test.tsx
- components/Authorization/loginForm.client.tsx
- jest.setup.cjs
Testing front end error for when a nonexistent user tries to log in.
Changes were made to the following files:
logInDetails.test.tsx : Probably not a good file name but can change later
loginform.client.tsx: Changed the component from a variable to a function
jest.setup.cjs: Added some new functions that needed mocking
> NEIG-92 Testing: Log In to Nonexistent User

- __test__/createEvent.test.tsx
- __test__/logInDetails.test.tsx
- components/CreateEventDrawer/CreateEventDrawer.tsx
- jest.setup.cjs
Implemented 8 unit tests to event creation, all tests successfully passes - reference to the screenshot for more details.
Changes were made to the following files:
* createEvent.test.tsx (_new_) : Implements the unit tests
* CreateEventDrawer.tsx: Added test ids to individual test components and refactored out image section given its pushed off to next sprint.
* jest.setup.cjs: Added new global mocks for testing
* Other minor changes/fixes
> NEIG-85 Testing: Create an Event

- components/UserList/UserList.tsx
https://github.com/br-cz/neighbourhood/assets/93398491/a49cdbac-4463-4dd0-90b2-9afef3ad1e81
Quick update. Fixed loading state as well as added a loader to the People page (UserList.tsx) so that the user has an idea of what's going on when they open this page and wait for us to fetch users.
> NEIG-123: Added Loader to People Page

- __test__/NeighbourhoodShell.test.tsx
- components/CommunityButton/CommunityButton.tsx
- components/Navbar/Navbar.tsx
- components/NeighbourhoodShell/NeighbourhoodShell.tsx
- components/UserButton/UserButton.tsx
- jest.setup.cjs
A test suite of unit tests for NeighbourhoodShell, as well as the Navbar and custom UserButton.tsx, CommunityButton.tsx components.
1. Renders the Shell correctly when authenticated
2. Renders the Header correctly
3. Renders the Navbar correctly
4. Renders the Navbar items correctly
5. Profile button is rendered with the correct info
6. Communities button is rendered with the correct info
7. Clicking the logout button presents a logout confirmation
> NEIG-120: Neighbourhood Shell Unit Tests

- __test__/People.test.tsx
- components/UserList/UserList.tsx
- components/UserListItem/UserListItem.tsx
New unit test suite for the "Connect with People" feature - incl. the People page, friendQueries.ts, as well as UserList.tsx and UserListItem.tsx components.
Includes 13 new unit tests:
1. Renders the initial People page correctly
2. Renders the user list correctly
3. Renders a list of user items correctly
4. Renders an appropriate # of user cards to members in the community
5. Renders user friends correctly
6. Renders incoming friend requests correctly
7. Renders outgoing friend requests correctly
8. Renders regular members (no relation to user) correctly
9. Clicks the add friend button and sends friend requests correctly
10. Cancels an outgoing friend request correctly
11. Declines an incoming friend request correctly
12. Accepts an incoming friend request correctly
13. Removes a friend …
> NEIG-100: Connect With People Unit Tests

- __test__/createPost.test.tsx
- components/CreatePostDrawer/CreatePostDrawer.tsx
- components/CreatePostDrawer/createPostValidation.ts
- jest.setup.cjs
Created 5 unit tests for post creation.
* createPost.test.tsx: Implements the unit tests
* CreatePostDrawers.tsx: Add test ids to test components
* jest.setup.cjs: Added new global mocks for testing
* createPostValidation.ts: Added min and max character length for post content validation
> NEIG-86-2 Testing: Create a Post

- __test__/createPost.test.tsx
Quick update to post creation tests - finished test for selecting & changing fields correctly
> NEIG-131: Finished Post Creation Test 4

- app/marketplace/page.tsx
- components/Marketplace/MarketplaceFeed.tsx
Search functionality for the Marketplace - allows searching via:
- Item Name
- Item Description
- Seller Name (First or Last)
> NEIG-158: Marketplace Search

- app/profile/page.tsx
- components/Marketplace/CreateListingDrawer.tsx
- components/Marketplace/createListingValidation.ts
- components/ProfileCard/CustomizeProfileModal.tsx
- components/ProfileCard/ProfileCard.module.css
- components/ProfileCard/ProfileCard.tsx
- components/ProfileCard/customizeProfileValidation.ts
- types/types.ts
https://github.com/br-cz/neighbourhood/assets/93398491/af80c712-b980-4142-b77b-b2cad9652255
Added a new modal (CustomizeProfileModal.tsx) that allows users to customize their profile (i.e. bio, contact, kids, pets, etc.).
This ticket includes frontend, validation schema, and image upload
Still requires valid submission (update User), and S3 integration
Also added loader to profile page, adjusted types, and fixed v small linting issues in marketplace while I was in those files
> NEIG-146: Customize Profile Card

- app/people/page.tsx
- components/UserList/UserList.tsx
- utils/sortUtils.ts
https://github.com/br-cz/neighbourhood/assets/93398491/3eace145-5fa2-4258-a198-d4be8c902735
Added searching to the people page, as well as a baseline for sorting (currently alphabetically by first name). Searches via full name (first/last), username, or bio (i.e. if you wanna look for other u of m students maybe? can remove this if need be)
EDIT: Also added sorting: first name (A-Z), last name (A-Z) or date joined
needs tests :) I love jest and regression testing :))))
> NEIG-142 & NEIG-25: People Search & Sort

- .github/workflows/deploy.yml
- Dockerfile
Add Dockerfile and deploy workflow to employ the CD pipeline
> BC-NEIG-157: Add CD pipeline

- .github/workflows/deploy.yml
> Upgrade build node ver to 18 to remove performance issue

- .github/workflows/deploy.yml
Missing config like in build and test
> Add amplify configuration in deployment

- components/UserListItem/UserListItem.tsx
- components/UserListItem/UserListItemPreview.tsx
- types/types.ts
Super quick update to user preview cards now that we have the schema update in - replaces placeholder data with real data. Note that most cards will show N/A right now since we dont have the setup in from account creation.
> NEIG-167: Replaced Preview Card Placeholder Data

- app/home/page.tsx
- components/UserList/UserList.tsx
- components/utils/postUtils.tsx
- utils/sortUtils.ts
https://github.com/br-cz/neighbourhood/assets/118633138/0dcc267d-70be-448e-b62d-21bc197590bb
Implemented sort functionality for the post feed with fully modular components + refactoring + new sort utility functions. 
* postUtils.tsx (_new_): New modular function to filter and sort posts based on sort query and search query.
* sortUtils.ts: Renamed one existing utility function + added a new one to sort by old to new items based on date.
*  home/page.tsx: Modified to integrate of the filter and sort functionality.
*  userList.tsx: Minor adjustment for the renamed utility function.
> NEIG-139: Post Sort/Filter Functionalities

- app/events/page.tsx
- app/home/page.tsx
- components/Marketplace/MarketplaceFeed.tsx
Implemented conditional rendering of posts, events and marketplace if there is no such entry in the community for that feed.
> NEIG-136: Conditional Rendering for Posts/Event/Marketplace Frontend

- utils/timeUtils.ts
* Added a datetoAge function to timeUtil
> NEIG-150: Get age from birthday function in timeUtil

- components/EventCard/EventCard.tsx
- components/utils/s3Helpers/CommunityImageS3Helper.tsx
- components/utils/s3Helpers/EventImageS3Helper.tsx
- components/utils/s3Helpers/ItemForSaleImageS3Helper.tsx
- components/utils/s3Helpers/PostImageS3Helper.tsx
- Cleaned up entries in database that had invalid s3 urls
- Remove errors for when image is not available
> Hotfix for S3 - Retrieval errors fix and clean up database

- components/utils/s3Helpers/EventImageS3Helper.tsx
- components/utils/s3Helpers/ItemForSaleImageS3Helper.tsx
- components/utils/utilFunctions.tsx
- added placeholder img in s3, will retrieve this image when none is available
> NEIG-172: Retrieve placeholder img for event/marketplace when none available

- __test__/SignUp.test.tsx
- app/communities/page.tsx
- components/CommunityButton/CommunityButton.tsx
- components/CommunityCard/CommunityCard.tsx
- components/CommunityListItem/CommunityListItem.tsx
- components/SelectCommunityModal/SelectCommunityModal.tsx
- components/SelectCommunityModal/selectCommunityModalValidation.ts
- components/SignUp/SelectCommunity.tsx
- components/SignUp/SignUp.tsx
- components/SignUp/signUpValidation.ts
Summary:
- selectedCommunity is now a single value and community selection is uni select
- Can't join more than 3
- Can't leave when only in 1 
- Can only see unjoined communities
https://cdn.discordapp.com/attachments/1203499416523374682/1216901214332260492/Screenshot_2024-03-11_at_7.10.48_PM.png?ex=66021292&is=65ef9d92&hm=9503e9bfd49c8c054ff1c72eab75abc8306e23b34abcd49db83b4c5a25074f21&https://cdn.discordapp.com/attachments/1203499416523374682/1216900033866108959/Screenshot_2024-03-11_at_7.06.08_PM.png?ex=66021178&is=65ef9c78&hm=5884e85b4091bf07d9b4150294bbf88aaced5cc03ea9d34fef4f6b999d3e192d&https://cdn.discordapp.com/attachments/1203499416523374682/1216899038675468430/Screenshot_2024-03-11_at_7.02.09_PM.png?ex=6602108b&is=65ef9b8b&hm=f8410003b36fd3645c864cbee14283d8d99dd4a698d2b2f9248d …
> Selected community hotfix

- __test__/CustomizeProfileModal.test.tsx
- __test__/Profile.test.tsx
- app/profile/page.tsx
- components/ProfileCard/CustomizeProfileModal.tsx
Series of tests for the profile page, ProfileCard component, as well as the CustomizeProfileModal component.
1.1 Renders the initial Profile page correctly
1.2 Renders the Profile Card correctly with the correct information
1.1 Renders the initial customize button correctly
1.2 Opens the modal when the customize button is clicked
1.3 Renders the modal correctly with the correct fields
1.4 Fields are usable and accept input
1.5 Valid inputs submit correctly
1.6 Invalid inputs do not submit correctly
1.7 Changing the profile picture file changes the preview image
1.8 Submitting a profile picture change stores it in S3
1.9 Customize profile modal can be closed
> NEIG-183+184: Profile Page, ProfileCard, + CustomizeProfileModal Unit Tests

- __test__/postFeed.test.tsx
- components/CommentCard/CommentCard.tsx
- components/PostCard/PostCard.tsx
Test suites for post comments as well as post likes. Provides coverage for PostCard.tsx and CommentCard.tsx components, all tests pass.
New Tests:
- Posts can be liked correctly
- Posts can be unliked correctly
- Comments are rendered correctly for a post
- Clicking "Comment" makes the comment input visible
- Submitting a valid comment works correctly
- Submitting an invalid comment results in an error notification
> NEIG-181+182: Post Likes + Comments Tests

- __test__/eventUtils.test.tsx
- __test__/peopleUtils.test.tsx
- __test__/postUtils.test.tsx
- app/events/page.tsx
- app/home/page.tsx
- components/EventCard/EventCard.tsx
- components/PostCard/PostCard.tsx
- components/utils/eventUtils.tsx
- components/utils/postUtils.tsx
- types/types.ts
- utils/sortUtils.ts
Various unit test suites to provide coverage for sortUtils.ts, eventUtils.ts, and postUtils.ts.
Also various types fixes to allow for mock data to be used - well tested so shouldnt cause any major changes.
> Event/Post/People Search and Sort Tests

- components/Authorization/loginForm.client.tsx
Quick fix to login. The await on signin was removed for some reason which was making us login and navigate to home before getting the data we need. Fixed now
> NEIG-193: Fixed Login not Retrieving Community Data

- __test__/SignUp.test.tsx
- app/communities/page.tsx
- app/communities/utils/communityUtils.tsx
- components/CommunityButton/CommunityButton.tsx
- components/CommunityCard/CommunityCard.module.css
- components/CommunityCard/CommunityCard.tsx
- components/CommunityListItem/CommunityListItem.module.css
- components/CommunityListItem/CommunityListItem.tsx
- components/SelectCommunityModal/SelectCommunityModal.tsx
- components/SelectCommunityModal/communitySelectHandler.tsx
- components/SignUp/AddressInput.tsx
- components/SignUp/SelectCommunity.tsx
- components/SignUp/SignUp.tsx
- components/UserButton/UserButton.tsx
- src/api/services/community.tsx
- src/hooks/communityCustomHooks.tsx
- src/hooks/usersCustomHooks.tsx
https://github.com/br-cz/neighbourhood/assets/93398491/7405c65a-493b-4f4a-9338-6b43d3b4365f
Originally a refactor of CommunityCard to fix the cutoff of the buttons due to the Grid setup, got carried away and did a larger refactor for usability
See vid
> NEIG-192: Fixed CommunityCard Button Cutoff + Refactor

- .github/workflows/build.yml
- .github/workflows/deploy.yml
> Add API key to process env in CICD

- __test__/People.test.tsx
- __test__/Profile.test.tsx
- components/ProfileCard/CustomizeProfileModal.tsx
- components/ProfileCard/ProfileCard.module.css
- components/ProfileCard/ProfileCard.tsx
- components/SignUp/ProfileSetup.module.css
- components/SignUp/ProfileSetup.tsx
- components/UserListItem/UserListItemPreview.tsx
- utils/timeUtils.ts
Gets age on profile card + profile previews + small fixes
> NEIG-177: Age on Profile Cards + Previews

- src/hooks/googleMapsAPI.tsx
> Remove env check for env var

- app/home/page.tsx
- components/Authorization/useAuth.ts
- utils/signOutUtils.ts
Added useEffect on async function to ensure the validation is waited upon. For some reason this doesnt work when only the function is called in useEffect, only works when the whole thing is in useEffect as well.
> Fix login validation issue

- app/app/page.tsx
> Change default to app from home to avoid 404

- components/Events/EventsPage.tsx
- components/utils/eventUtils.tsx
- utils/sortUtils.ts
Sort events by upcoming - that is, by datetime soonest to occur
> NEIG-238: Sort Events by Upcoming

- __test__/NeighbourhoodShell.test.tsx
- __test__/createPost.test.tsx
- __test__/eventFeed.test.tsx
- __test__/integration/eventsPage.test.tsx
- __test__/marketplaceFeed.test.tsx
- __test__/postFeed.test.tsx
- components/Events/EventCard/EventCard.module.css
- components/Events/EventCard/EventCard.tsx
- components/Events/EventFeed/EventFeed.tsx
- components/Events/EventsPage.tsx
- components/Home/PostCard/PostCard.tsx
- components/Home/PostFeed/PostFeed.tsx
- components/Marketplace/MarketplaceCard.tsx
- components/Marketplace/MarketplaceFeed.tsx
- components/Marketplace/MarketplacePage.tsx
- src/api/services/event.tsx
- src/api/services/marketplace.tsx
- src/api/services/post.tsx
- src/hooks/eventsCustomHooks.tsx
- src/hooks/marketplaceCustomHooks.tsx
- utils/sortUtils.ts
Title
Based off of event deletion branch
> NEIG-74: Delete Marketplace Listings

- __test__/integration/homePage.test.tsx
- __test__/integration/marketPlace.test.tsx
- __test__/integration/profile.test.tsx
- __test__/integration/search.test.tsx
Based off of previous refactor branch
> Test refactor
